### PR TITLE
Looking for config files at the root of the repository before current folder

### PR DESCRIPTION
**Pull request by bhigy**

### CODE REVIEW

**Comment by egpbos** [comment]
I think that depending on how you install, the path you take there is not actually the repo path (it could be if you install in dev mode, i.e. `pip install -e .`), but rather the install path (somewhere in your conda environment or lib/pythonX.X/site-packages/..), isn't it?

Maybe in the long run we should make the config file path a command line option. Is that something that would work here as well?

**Comment by bhigy** [comment]
And what about a location such as ~/.platalea/config.yml?

**Comment by egpbos** [comment]
Good idea!

**Comment by egpbos** [comment]
Looks good to me!

**Pull request merged**
